#index:
#    path: /
#    controller: App\Controller\DefaultController::index


blog:
    path: /blog
    controller: App\Controller\MyController::blog

galeria:
    path: /galeria
    controller: App\Controller\MyController::galeria

contacto:
    path: /contacto
    controller: App\Controller\MyController::contacto

reservaCita:
    path: /registra-create
    controller: App\Controller\RegistraController::index

usuarios:
    path: /usuario
    controller: App\Controller\UsuarioController::index

register:
    path: /register
    controller: App\Controller\UsuarioController::create
logout:
    path: /logout